DROP TABLE CARD_PAY_MNG IF EXISTS; 
CREATE TABLE CARD_PAY_MNG ( 
    MNG_NO VARCHAR(20) NOT NULL, 
    DATA_DIV VARCHAR(1) NOT NULL, 
    CARD_DATA CHAR(450) NOT NULL, 
    CANCEL_YN VARCHAR(1), 
    CANCEL_MNG_NO VARCHAR(20),
    INPUTDATE TIMESTAMP NOT NULL,
    primary key (MNG_NO) 
);